# Generated by Django 3.1.4 on 2021-01-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_id', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('tournament_id', models.CharField(blank=True, max_length=70)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.season')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, choices=[('TOP', 'Top'), ('JG', 'Jungle'), ('MID', 'Mid'), ('ADC', 'ADC'), ('SUPP', 'Support')], max_length=10)),
                ('account_id', models.CharField(blank=True, max_length=70)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_format', models.IntegerField(choices=[(1, 'Best of 1'), (3, 'Best of 3')])),
                ('week', models.IntegerField(default=1)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.season')),
                ('teams', models.ManyToManyField(related_name='matches', to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_id', models.CharField(blank=True, max_length=100)),
                ('tournament_code', models.CharField(blank=True, max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app.match')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='app.team')),
            ],
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='app_team_name_d8f293_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'season')},
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['number'], name='app_season_number_731c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['account_id'], name='app_player_account_402350_idx'),
        ),
    ]
