# Generated by Django 3.1.4 on 2020-12-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'season')},
        ),
    ]
