# Generated by Django 3.1.4 on 2021-01-07 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.team'),
        ),
    ]
