# Generated by Django 3.1.4 on 2021-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summoner_name',
            field=models.CharField(max_length=32),
        ),
    ]
