# Generated by Django 3.1.4 on 2021-01-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_match_winning_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winning_team',
        ),
    ]
