# Generated by Django 3.1.4 on 2020-12-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201221_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
