# Generated by Django 3.1.4 on 2021-04-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210401_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='heard_from',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='summoner_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
