# Generated by Django 3.1.4 on 2021-01-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_match_winning_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_in_series',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
