# Generated by Django 3.1.4 on 2021-04-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210401_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_username',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='summoner_name',
            field=models.CharField(max_length=64),
        ),
    ]
