# Generated by Django 3.1.4 on 2020-12-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201221_0041'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['username'], name='app_player_usernam_ec7a01_idx'),
        ),
    ]
