# Generated by Django 3.1.4 on 2021-01-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_game_game_in_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='meta_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
