# Generated by Django 3.1.4 on 2020-12-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201221_0047'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='app_player_usernam_ec7a01_idx',
        ),
        migrations.AlterField(
            model_name='player',
            name='account_id',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['account_id'], name='app_player_account_402350_idx'),
        ),
    ]
