# Generated by Django 3.1.4 on 2021-05-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210426_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='twitch_vod',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
