# Generated by Django 3.1.4 on 2021-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210107_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='games', to='app.Team'),
        ),
    ]
