# Generated by Django 3.1.4 on 2021-01-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_game_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teams',
        ),
    ]
