# Generated by Django 3.1.4 on 2021-05-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_match_twitch_vod'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mvp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mvps', to='app.player', null=True, blank=True),
            preserve_default=False,
        ),
    ]
