# Generated by Django 3.1.4 on 2021-05-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_game_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_side',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
