# Generated by Django 3.1.4 on 2021-01-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_game_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='caster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['caster'], name='app_player_caster_e565e8_idx'),
        ),
    ]
