# Generated by Django 3.1.4 on 2020-12-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='account_id',
            field=models.CharField(max_length=20),
        ),
    ]
