# Generated by Django 3.1.4 on 2020-12-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201223_0625'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='app_player_account_402350_idx',
        ),
        migrations.RemoveField(
            model_name='player',
            name='account_id',
        ),
    ]
