# Generated by Django 3.1.4 on 2020-12-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201223_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='account_id',
            field=models.CharField(blank=True, max_length=70, unique=True),
        ),
    ]
