# Generated by Django 3.1.4 on 2021-04-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_registrationform_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='discord_user_id',
            field=models.BigIntegerField(),
        ),
    ]
