# Generated by Django 3.1.4 on 2021-05-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_game_game_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('kda_per_game', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('vision_per_min', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('cc_per_game', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app.player')),
            ],
        ),
    ]
