# Generated by Django 3.1.4 on 2020-12-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_player_account_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['account_id'], name='app_player_account_402350_idx'),
        ),
    ]
