# Generated by Django 3.1.4 on 2020-12-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201223_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('JG', 'Jungle'), ('MID', 'Mid'), ('ADC', 'ADC'), ('SUPP', 'Support')], max_length=10),
        ),
    ]
