# Generated by Django 3.1.4 on 2021-05-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210527_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='cs_per_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
