# Generated by Django 3.1.4 on 2021-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_playerstats_cs_per_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='cc_per_game',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='cs_per_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='kda_per_game',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='vision_per_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
