# Generated by Django 3.1.4 on 2020-12-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201225_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scheduled_for',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', to='app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losing_matches', to='app.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_matches', to='app.team'),
        ),
    ]
