# Generated by Django 3.1.4 on 2021-05-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210527_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='kp_per_game',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
