# Generated by Django 3.1.4 on 2021-01-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.provider'),
        ),
        migrations.AddField(
            model_name='season',
            name='tournament_id',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
