# Generated by Django 3.1.4 on 2021-06-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_playerstats_damage_per_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='assists',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='deaths',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='kills',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
