# Generated by Django 3.1.4 on 2021-01-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210106_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.provider'),
        ),
    ]
