# Generated by Django 3.1.4 on 2021-06-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210618_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='damage_taken',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
