# Generated by Django 3.1.4 on 2021-01-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201228_1316'),
        ('app', '0018_auto_20210106_2016'),
    ]

    operations = [
    ]
