# Generated by Django 3.1.4 on 2021-06-21 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_playerstats_damage_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerChampionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.IntegerField()),
                ('games_played', models.IntegerField(default=0)),
                ('kills', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deaths', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assists', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('kda', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vision_per_min', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cs_per_min', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('kp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('damage_per_min', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('damage_taken', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
        ),
    ]
