# Generated by Django 3.1.4 on 2021-06-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_playerchampionstats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerchampionstats',
            unique_together={('player', 'champion_id')},
        ),
    ]
