# Generated by Django 3.1.4 on 2021-06-22 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210622_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerchampionstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_champion_stats', to='app.player'),
        ),
    ]
