# Generated by Django 3.1.4 on 2021-06-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210622_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_icon_id',
            field=models.IntegerField(default=0),
        ),
    ]
