# Generated by Django 3.1.4 on 2021-07-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_player_profile_icon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='playoff_fraction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
