# Generated by Django 3.1.4 on 2021-09-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210716_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='wants_to_be_captain',
            field=models.BooleanField(default=False),
        ),
    ]
