# Generated by Django 3.1.4 on 2022-05-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_team_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
