# Generated by Django 3.1.4 on 2022-05-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_season_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summoner_level',
            field=models.IntegerField(default=1),
        ),
    ]
