# Generated by Django 3.1.4 on 2022-05-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_user_summoner_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='discord_channel_id',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='discord_role_id',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
