# Generated by Django 3.1.4 on 2022-05-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220512_2259'),
        ('app', '0032_auto_20220512_2150'),
    ]

    operations = [
    ]
