# Generated by Django 3.1.4 on 2022-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220512_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.IntegerField(default=16777215),
        ),
        migrations.AlterField(
            model_name='team',
            name='discord_channel_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='discord_role_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
