# Generated by Django 3.1.4 on 2022-05-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20220512_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='discord_channel_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='discord_role_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
