# Generated by Django 3.1.4 on 2022-05-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20220513_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_updated_discord_info',
            field=models.DateTimeField(null=True),
        ),
    ]
