# Generated by Django 3.1.4 on 2022-05-14 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_user_last_updated_discord_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='smurf_account_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=70), null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='smurfs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=64), null=True, size=None),
        ),
    ]
