# Generated by Django 3.1.4 on 2022-05-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20220514_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='proposed_for',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
