# Generated by Django 3.1.4 on 2022-05-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_match_proposed_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
