# Generated by Django 3.1.4 on 2022-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_old_data_format',
            field=models.BooleanField(default=False),
        ),
    ]
