# Generated by Django 3.1.4 on 2022-05-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_game_is_old_data_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event_id',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
