# Generated by Django 3.1.4 on 2022-05-21 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_user_summoner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='casters',
            field=models.ManyToManyField(related_name='caster_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
