# Generated by Django 3.1.4 on 2022-05-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20220520_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mvp_votes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
