# Generated by Django 3.1.4 on 2022-07-09 00:31

import app.utils
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_game_mvp_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('JG', 'Jungle'), ('MID', 'Mid'), ('ADC', 'ADC'), ('SUPP', 'Support')], max_length=10), default=app.utils.get_role_choices_default, size=None),
        ),
        migrations.AddField(
            model_name='season',
            name='is_rumble',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RumbleWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rumble_weeks', to='app.season')),
            ],
        ),
        migrations.CreateModel(
            name='RumbleTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(related_name='rumble_teams', to='app.Player')),
                ('rumble_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app.rumbleweek')),
            ],
        ),
    ]
