# Generated by Django 3.1.4 on 2022-07-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20220708_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='highest_rank',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='is_rumble',
            field=models.BooleanField(default=False),
        ),
    ]
