# Generated by Django 3.1.4 on 2022-07-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20220708_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_rumble',
            field=models.BooleanField(default=False),
        ),
    ]
