# Generated by Django 3.1.4 on 2022-07-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_player_is_rumble'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='proposed_rumble_elo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rumble_elo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
