# Generated by Django 3.1.4 on 2022-07-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20220708_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_rumble_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_rumble_player',
            field=models.BooleanField(default=False),
        ),
    ]
