# Generated by Django 3.1.4 on 2022-07-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20220709_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.season'),
        ),
    ]
