# Generated by Django 3.1.4 on 2022-07-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20220709_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='RumbleSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ManyToManyField(related_name='signups', to='app.Player')),
                ('rumble_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.rumbleweek')),
            ],
        ),
    ]
