# Generated by Django 3.1.4 on 2022-07-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_rumblesignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumblesignup',
            name='player',
        ),
        migrations.AddField(
            model_name='rumblesignup',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='app.player'),
        ),
    ]
