# Generated by Django 3.1.4 on 2022-07-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20220709_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumbleweek',
            name='signups_open',
            field=models.BooleanField(default=False),
        ),
    ]
