# Generated by Django 3.1.4 on 2022-07-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_rumbleweek_signups_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumbleweek',
            name='signups_open',
            field=models.BooleanField(default=True),
        ),
    ]
