# Generated by Django 3.1.4 on 2022-07-11 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20220711_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumbleweek',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='rumbleweek',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
