# Generated by Django 3.1.4 on 2022-07-12 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20220711_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elo_difference',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_rumble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='role_pref_coefficient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='rumble_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.rumbleweek'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_rumble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='rumble_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app.rumbleweek'),
        ),
        migrations.AlterField(
            model_name='match',
            name='casters',
            field=models.ManyToManyField(blank=True, null=True, related_name='caster_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rumbleteam',
            name='rumble_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rumble_teams', to='app.rumbleweek'),
        ),
    ]
