# Generated by Django 3.1.4 on 2022-07-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20220711_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='elo_difference',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='role_pref_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
