# Generated by Django 3.1.4 on 2022-07-13 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20220711_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rumble_adc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_adc', to='app.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='rumble_jg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_jg', to='app.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='rumble_mid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_mid', to='app.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='rumble_supp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_supp', to='app.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='rumble_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_top', to='app.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='casters',
            field=models.ManyToManyField(blank=True, related_name='caster_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
