# Generated by Django 3.1.4 on 2022-07-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20220712_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rumble_teams',
        ),
    ]
