# Generated by Django 3.1.4 on 2022-07-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_rumbleweek_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='role_preferences',
        ),
    ]
