# Generated by Django 3.1.4 on 2022-07-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_player_role_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_timeline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
