# Generated by Django 3.1.4 on 2022-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_match_on_game_in_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='event_id',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
