# Generated by Django 3.1.4 on 2022-07-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20220714_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_rumble_priority',
            field=models.BooleanField(default=False),
        ),
    ]
