# Generated by Django 3.1.4 on 2022-07-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_player_has_rumble_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reached', models.BooleanField(default=False)),
            ],
        ),
    ]
