# Generated by Django 3.1.4 on 2022-07-21 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_user_is_blacklisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.IntegerField(default=1)),
                ('discord_role_id', models.CharField(max_length=64)),
                ('color', models.IntegerField(default=16777215)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='rumble_lp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rumble_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.rank'),
        ),
    ]
