# Generated by Django 3.1.4 on 2022-07-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20220721_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='discord_role_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
