# Generated by Django 3.2 on 2022-07-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20220721_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_rumble_ready',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proposed_rumble_elo',
        ),
    ]
