# Generated by Django 3.2 on 2022-07-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_remove_rank_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='is_top_rank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rank',
            name='upper_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
