# Generated by Django 3.2 on 2022-07-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20220727_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='upper_percentage',
            new_name='threshold_percentile',
        ),
        migrations.AddField(
            model_name='rank',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
