# Generated by Django 3.2 on 2022-07-27 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20220727_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rumble_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='app.rank'),
        ),
    ]
