# Generated by Django 3.2 on 2022-07-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_alter_player_rumble_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='threshold_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
