# Generated by Django 3.2 on 2022-07-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_alter_rank_threshold_percentile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avg_rumble_elo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
