# Generated by Django 3.2 on 2022-07-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_auto_20220729_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='banned_role',
            field=models.CharField(blank=True, choices=[('top', 'top'), ('jungle', 'jungle'), ('mid', 'mid'), ('bot', 'bot'), ('support', 'support')], max_length=10),
        ),
    ]
