# Generated by Django 3.2 on 2022-08-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rumble_old_elo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
